### ISSUE TITLE
Bump reqwest to v0.11.0

### ISSUE THREAD

**Issue by SwampertX** [fluminurs/fluminurs#615]
Since v1.1.7, there is a conflict in dependencies, namely `reqwest` depends on `tokio` v0.2.x while we use `tokio` >= v0.3. I encountered the runtime error below:

```
Username (include the nusstu\ prefix):
Password:
thread 'main' panicked at 'not currently running on the Tokio runtime.', /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/handle.rs:118:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: tokio::runtime::handle::Handle::current
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/handle.rs:118:9
   5: tokio::runtime::blocking::pool::spawn_blocking
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/runtime/blocking/pool.rs:69:14
   6: tokio::task::blocking::spawn_blocking
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.23/src/task/blocking.rs:130:9
   7: <hyper::client::connect::dns::GaiResolver as tower_service::Service<hyper::client::connect::dns::Name>>::call
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/client/connect/dns.rs:120:24
   8: <S as hyper::client::connect::dns::sealed::Resolve>::resolve
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/client/connect/dns.rs:344:13
   9: hyper::client::connect::dns::resolve::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/client/connect/dns.rs:354:5
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  11: hyper::client::connect::http::HttpConnector<R>::call_async::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/client/connect/http.rs:327:25
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: <hyper::client::connect::http::HttpConnector<R> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/client/connect/http.rs:268:40
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  16: <hyper::client::connect::http::HttpConnecting<R> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/client/connect/http.rs:409:9
  17: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/either.rs:63:36
  18: <hyper_tls::client::HttpsConnector<T> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-tls-0.4.3/src/client.rs:127:23
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  21: <hyper_tls::client::HttpsConnecting<T> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-tls-0.4.3/src/client.rs:156:9
  22: reqwest::connect::Connector::connect_with_maybe_proxy::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/connect.rs:347:26
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  24: reqwest::connect::with_timeout::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/connect.rs:512:9
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  27: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/service/oneshot.rs:50:28
  28: <F as futures_core::future::TryFuture>::try_poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.8/src/future.rs:83:9
  29: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/try_future/into_future.rs:31:9
  30: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/map.rs:49:37
  31: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  32: <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  33: <F as futures_core::future::TryFuture>::try_poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.8/src/future.rs:83:9
  34: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/try_future/into_future.rs:31:9
  35: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/map.rs:49:37
  36: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  37: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  38: <F as futures_core::future::TryFuture>::try_poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.8/src/future.rs:83:9
  39: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/try_future/try_flatten.rs:45:34
  40: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  41: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  42: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/either.rs:63:36
  43: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/common/lazy.rs:59:27
  44: futures_util::future::future::FutureExt::poll_unpin
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/mod.rs:561:9
  45: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/select.rs:92:36
  46: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/map.rs:49:37
  47: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  48: <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/flatten.rs:45:36
  49: <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  50: <F as futures_core::future::TryFuture>::try_poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.8/src/future.rs:83:9
  51: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/try_future/into_future.rs:31:9
  52: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/future/map.rs:49:37
  53: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  54: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  55: <F as futures_core::future::TryFuture>::try_poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.8/src/future.rs:83:9
  56: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/try_future/try_flatten.rs:45:34
  57: <futures_util::future::try_future::TryFlatten<Fut1,Fut2> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  58: <futures_util::future::try_future::AndThen<Fut1,Fut2,F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/lib.rs:113:13
  59: hyper::client::Client<C,B>::retryably_send_request::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/client/mod.rs:256:26
  60: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/future/poll_fn.rs:54:9
  61: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  62: <hyper::client::ResponseFuture as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.13.9/src/client/mod.rs:628:9
  63: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/async_impl/client.rs:1381:29
  64: <reqwest::async_impl::client::Pending as core::future::future::Future>::poll
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/async_impl/client.rs:1360:51
  65: fluminurs::api::infinite_retry_http::{{closure}}
             at ./src/api/mod.rs:162:19
  66: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  67: fluminurs::api::auth_http_post::{{closure}}
             at ./src/api/mod.rs:176:5
  68: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  69: fluminurs::api::Api::with_login::{{closure}}
             at ./src/api/mod.rs:276:13
  70: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  71: fluminurs::main::{{closure}}
             at ./src/main.rs:324:15
  72: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  73: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/park/thread.rs:263:54
  74: tokio::coop::with_budget::{{closure}}
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/coop.rs:121:9
  75: std::thread::local::LocalKey<T>::try_with
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  76: std::thread::local::LocalKey<T>::with
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  77: tokio::coop::with_budget
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/coop.rs:114:5
  78: tokio::coop::budget
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/coop.rs:98:5
  79: tokio::park::thread::CachedParkThread::block_on
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/park/thread.rs:263:31
  80: tokio::runtime::enter::Enter::block_on
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/runtime/enter.rs:151:13
  81: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/runtime/thread_pool/mod.rs:71:9
  82: tokio::runtime::Runtime::block_on
             at /home/titanx/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.0.1/src/runtime/mod.rs:452:43
  83: fluminurs::main
             at ./src/main.rs:248:1
  84: core::ops::function::FnOnce::call_once
             at /home/titanx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
After some digging, I found it to be a `reqwest` issue. See https://github.com/seanmonstar/reqwest/issues/1108 for a similar error.

This problem is solved on my machine by using `reqwest` v0.11.0, which was released a few days ago. I will be submitting a PR along this issue shortly.

**Comment by tysg** [comment]
Confirmed this PR fixes the issue on my Mac as well
