### ISSUE TITLE
Error after loading credentials: thread 'main' panicked at 'not currently running on the Tokio runtime.'

### ISSUE THREAD

**Issue by btzy** [fluminurs/fluminurs#619]
To reproduce, just run fluminurs, type in your credentials, and watch the panic happen.  I think it was okay 1-2 months ago, so I would think it's due to a recent dependency bump.  Error occurs on both debug and release builds.

System: Windows 10, Rust 1.49.0 stable-x86_64-pc-windows-msvc

```
C:\Users\AdminCOOP\Documents\GitHub\fluminurs>cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.31s
     Running `target\debug\fluminurs.exe`
Username (include the nusstu\ prefix): nusstu\<my real username>
Password:
thread 'main' panicked at 'not currently running on the Tokio runtime.', C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.23\src\runtime\handle.rs:118:28
stack backtrace:
   0:     0x7ff7cd63baae - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:108
   1:     0x7ff7cd63baae - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7cd63baae - std::sys_common::backtrace::_print_fmt
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff7cd63baae - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff7cd6539db - core::fmt::write
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\core\src\fmt\mod.rs:1078
   5:     0x7ff7cd633678 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\io\mod.rs:1518
   6:     0x7ff7cd63e8ed - std::sys_common::backtrace::_print
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff7cd63e8ed - std::sys_common::backtrace::print
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff7cd63e8ed - std::panicking::default_hook::{{closure}}
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:208
   9:     0x7ff7cd63e4c8 - std::panicking::default_hook
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:227
  10:     0x7ff7cd63f25f - std::panicking::rust_panic_with_hook
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:593
  11:     0x7ff7cd63ed61 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:499
  12:     0x7ff7cd63c3ef - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff7cd63ecb9 - std::panicking::begin_panic_handler
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:495
  14:     0x7ff7cd652210 - core::panicking::panic_fmt
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\core\src\panicking.rs:92
  15:     0x7ff7cd651f92 - core::option::expect_failed
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\core\src\option.rs:1260
  16:     0x7ff7cd353343 - core::option::Option<tokio::runtime::handle::Handle>::expect<tokio::runtime::handle::Handle>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\option.rs:349
  17:     0x7ff7cd378c46 - tokio::runtime::handle::Handle::current
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.23\src\runtime\handle.rs:118
  18:     0x7ff7cd266e54 - tokio::runtime::blocking::pool::spawn_blocking<closure-0,core::result::Result<hyper::client::connect::dns::IpAddrs, std::io::error::Error>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.23\src\runtime\blocking\pool.rs:69
  19:     0x7ff7cd228c98 - tokio::task::blocking::spawn_blocking<closure-0,core::result::Result<hyper::client::connect::dns::IpAddrs, std::io::error::Error>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.23\src\task\blocking.rs:130
  20:     0x7ff7cd26194d - hyper::client::connect::dns::{{impl}}::call
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\client\connect\dns.rs:120
  21:     0x7ff7cd02fd8d - hyper::client::connect::dns::sealed::{{impl}}::resolve<hyper::client::connect::dns::GaiResolver>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\client\connect\dns.rs:344
  22:     0x7ff7cd02ed1f - hyper::client::connect::dns::resolve::{{closure}}<hyper::client::connect::dns::GaiResolver>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\client\connect\dns.rs:354
  23:     0x7ff7ccf4b293 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  24:     0x7ff7cd070001 - hyper::client::connect::http::{{impl}}::call_async::{{closure}}<hyper::client::connect::dns::GaiResolver>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\client\connect\http.rs:327
  25:     0x7ff7ccf4a660 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  26:     0x7ff7cd062c41 - hyper::client::connect::http::{{impl}}::call::{{closure}}<hyper::client::connect::dns::GaiResolver>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\client\connect\http.rs:268
  27:     0x7ff7ccf4a0a0 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  28:     0x7ff7ccf97f0d - core::future::future::{{impl}}::poll<alloc::boxed::Box<Future, alloc::alloc::Global>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\future.rs:119
  29:     0x7ff7cd0629b1 - hyper::client::connect::http::{{impl}}::poll<hyper::client::connect::dns::GaiResolver>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\client\connect\http.rs:409
  30:     0x7ff7ccfdf1fa - futures_util::future::either::{{impl}}::poll<hyper::client::connect::http::HttpConnecting<hyper::client::connect::dns::GaiResolver>,hyper::client::connect::http::HttpConnecting<hyper::client::connect::dns::GaiResolver>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\either.rs:63
  31:     0x7ff7cd01e08a - hyper_tls::client::{{impl}}::call::{{closure}}<reqwest::connect::HttpConnector>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-tls-0.4.3\src\client.rs:127
  32:     0x7ff7ccf4adb3 - core::future::from_generator::{{impl}}::poll<generator-1>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  33:     0x7ff7ccf9804d - core::future::future::{{impl}}::poll<alloc::boxed::Box<Future, alloc::alloc::Global>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\future.rs:119
  34:     0x7ff7cd030c34 - hyper_tls::client::{{impl}}::poll<tokio::net::tcp::stream::TcpStream>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-tls-0.4.3\src\client.rs:156
  35:     0x7ff7cd03e8ba - reqwest::connect::{{impl}}::connect_with_maybe_proxy::{{closure}}
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.10.10\src\connect.rs:347
  36:     0x7ff7ccf4aeda - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  37:     0x7ff7cd042505 - reqwest::connect::with_timeout::{{closure}}<reqwest::connect::Conn,core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.10.10\src\connect.rs:512
  38:     0x7ff7ccf4ac4a - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  39:     0x7ff7ccf97fad - core::future::future::{{impl}}::poll<alloc::boxed::Box<Future, alloc::alloc::Global>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\future.rs:119
  40:     0x7ff7ccf68efb - hyper::service::oneshot::{{impl}}::poll<reqwest::connect::Connector,http::uri::Uri>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\service\oneshot.rs:50
  41:     0x7ff7ccf55a0b - futures_core::future::{{impl}}::try_poll<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>,reqwest::connect::Conn,alloc::boxed::Box<Error, alloc::alloc::Global>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-core-0.3.8\src\future.rs:83
  42:     0x7ff7ccf86811 - futures_util::future::try_future::into_future::{{impl}}::poll<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\try_future\into_future.rs:31
  43:     0x7ff7cd06167d - futures_util::future::future::map::{{impl}}::poll<futures_util::future::try_future::into_future::IntoFuture<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>>,futures_util::fns::MapErrFn<fn(alloc::boxed::Box<Error, alloc::alloc
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\future\map.rs:49
  44:     0x7ff7ccf4bb81 - futures_util::future::future::{{impl}}::poll<futures_util::future::try_future::into_future::IntoFuture<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>>,futures_util::fns::MapErrFn<fn(alloc::boxed::Box<Error, alloc::alloc::Glo
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  45:     0x7ff7ccf19d11 - futures_util::future::try_future::{{impl}}::poll<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>,fn(alloc::boxed::Box<Error, alloc::alloc::Global>) -> hyper::error::Error>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  46:     0x7ff7ccf29edb - futures_core::future::{{impl}}::try_poll<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, alloc::alloc::Global>) -> hyper::error::Error>,reqwest::connect::C
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-core-0.3.8\src\future.rs:83
  47:     0x7ff7ccf86771 - futures_util::future::try_future::into_future::{{impl}}::poll<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, alloc::alloc::Global>) -> hyper::error::Error
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\try_future\into_future.rs:31
  48:     0x7ff7cd0618ee - futures_util::future::future::map::{{impl}}::poll<futures_util::future::try_future::into_future::IntoFuture<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error,
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\future\map.rs:49
  49:     0x7ff7ccf4bb31 - futures_util::future::future::{{impl}}::poll<futures_util::future::try_future::into_future::IntoFuture<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, allo
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  50:     0x7ff7ccf19b51 - futures_util::future::try_future::{{impl}}::poll<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, alloc::alloc::Global>) -> hyper::error::Error>,closure-0>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  51:     0x7ff7ccf29e4b - futures_core::future::{{impl}}::try_poll<futures_util::future::try_future::MapOk<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, alloc::alloc::Global>) ->
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-core-0.3.8\src\future.rs:83
  52:     0x7ff7cd0220d5 - futures_util::future::try_future::try_flatten::{{impl}}::poll<futures_util::future::try_future::MapOk<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, alloc
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\try_future\try_flatten.rs:45
  53:     0x7ff7ccf19e41 - futures_util::future::try_future::{{impl}}::poll<futures_util::future::try_future::MapOk<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, alloc::alloc::Glob
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  54:     0x7ff7ccf19f31 - futures_util::future::try_future::{{impl}}::poll<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, alloc::alloc::Global>) -> hyper::error::Error>,futures_uti
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  55:     0x7ff7ccfdec5a - futures_util::future::either::{{impl}}::poll<futures_util::future::try_future::AndThen<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::boxed::Box<Error, alloc::alloc::Global
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\either.rs:63
  56:     0x7ff7ccf144e5 - hyper::common::lazy::{{impl}}::poll<closure-0,futures_util::future::either::Either<futures_util::future::try_future::AndThen<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::connect::Connector, http::uri::Uri>, fn(alloc::
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\common\lazy.rs:59
  57:     0x7ff7ccefaa0d - futures_util::future::future::FutureExt::poll_unpin<hyper::common::lazy::Lazy<closure-0, futures_util::future::either::Either<futures_util::future::try_future::AndThen<futures_util::future::try_future::MapErr<hyper::service::oneshot::Oneshot<reqwest::conn
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\future\mod.rs:561
  58:     0x7ff7ccf1616a - futures_util::future::select::{{impl}}::poll<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>,hyper::common::lazy::Lazy<closure-0, futures_util::future::either::Either<futures_util::future::try_future::AndThe
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\select.rs:92
  59:     0x7ff7cd062770 - futures_util::future::future::map::{{impl}}::poll<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper::common::lazy::Lazy<closure-0, futures_util::future::either::Eith
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\future\map.rs:49
  60:     0x7ff7ccf4bc71 - futures_util::future::future::{{impl}}::poll<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper::common::lazy::Lazy<closure-0, futures_util::future::either::Either<fu
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  61:     0x7ff7ccf87dac - futures_util::future::future::flatten::{{impl}}::poll<futures_util::future::future::Map<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper::common::lazy::Lazy<closure
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\future\flatten.rs:45
  62:     0x7ff7ccf336d1 - futures_util::future::future::{{impl}}::poll<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper::common::lazy::Lazy<closure-0, futures_util::future::either::Either<fu
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  63:     0x7ff7ccf3f1fb - futures_core::future::{{impl}}::try_poll<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper::common::lazy::Lazy<closure-0, futures_
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-core-0.3.8\src\future.rs:83
  64:     0x7ff7ccf869a1 - futures_util::future::try_future::into_future::{{impl}}::poll<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper::common::lazy::Laz
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\try_future\into_future.rs:31
  65:     0x7ff7cd060331 - futures_util::future::future::map::{{impl}}::poll<futures_util::future::try_future::into_future::IntoFuture<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\future\map.rs:49
  66:     0x7ff7ccf4bda1 - futures_util::future::future::{{impl}}::poll<futures_util::future::try_future::into_future::IntoFuture<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::bod
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  67:     0x7ff7ccf19a61 - futures_util::future::try_future::{{impl}}::poll<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper::common::lazy::Lazy<closure-0,
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  68:     0x7ff7ccf29f3b - futures_core::future::{{impl}}::try_poll<futures_util::future::try_future::MapOk<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-core-0.3.8\src\future.rs:83
  69:     0x7ff7cd0227cd - futures_util::future::try_future::try_flatten::{{impl}}::poll<futures_util::future::try_future::MapOk<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\try_future\try_flatten.rs:45
  70:     0x7ff7ccf19df1 - futures_util::future::try_future::{{impl}}::poll<futures_util::future::try_future::MapOk<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  71:     0x7ff7ccf19f81 - futures_util::future::try_future::{{impl}}::poll<futures_util::future::future::Then<futures_util::future::select::Select<hyper::client::pool::Checkout<hyper::client::PoolClient<reqwest::async_impl::body::ImplStream>>, hyper::common::lazy::Lazy<closure-0,
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\lib.rs:113
  72:     0x7ff7ccf62be0 - hyper::client::{{impl}}::retryably_send_request::{{closure}}<reqwest::connect::Connector,reqwest::async_impl::body::ImplStream>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\client\mod.rs:256
  73:     0x7ff7cd03120d - futures_util::future::poll_fn::{{impl}}::poll<core::result::Result<http::response::Response<hyper::body::body::Body>, hyper::error::Error>,closure-0>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.8\src\future\poll_fn.rs:54
  74:     0x7ff7cd21f7ad - core::future::future::{{impl}}::poll<alloc::boxed::Box<Future, alloc::alloc::Global>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\future.rs:119
  75:     0x7ff7cd25d524 - hyper::client::{{impl}}::poll
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\hyper-0.13.9\src\client\mod.rs:628
  76:     0x7ff7ccf3064a - reqwest::async_impl::client::{{impl}}::poll
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.10.10\src\async_impl\client.rs:1381
  77:     0x7ff7ccf302ff - reqwest::async_impl::client::{{impl}}::poll
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\reqwest-0.10.10\src\async_impl\client.rs:1360
  78:     0x7ff7ccd1948a - fluminurs::api::infinite_retry_http::{{closure}}<closure-0>
                               at C:\Users\AdminCOOP\Documents\GitHub\fluminurs\src\api\mod.rs:162
  79:     0x7ff7ccd542c3 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  80:     0x7ff7ccd1afd2 - fluminurs::api::auth_http_post::{{closure}}
                               at C:\Users\AdminCOOP\Documents\GitHub\fluminurs\src\api\mod.rs:176
  81:     0x7ff7ccd530f3 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  82:     0x7ff7ccd1e86f - fluminurs::api::{{impl}}::with_login::{{closure}}
                               at C:\Users\AdminCOOP\Documents\GitHub\fluminurs\src\api\mod.rs:277
  83:     0x7ff7ccd5509a - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  84:     0x7ff7ccd41812 - fluminurs::main::{{closure}}
                               at C:\Users\AdminCOOP\Documents\GitHub\fluminurs\src\main.rs:324
  85:     0x7ff7ccd538ca - core::future::from_generator::{{impl}}::poll<generator-0>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\future\mod.rs:80
  86:     0x7ff7ccd65ff8 - tokio::park::thread::{{impl}}::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\park\thread.rs:263
  87:     0x7ff7ccd3a60f - tokio::coop::with_budget::{{closure}}<core::task::poll::Poll<core::result::Result<tuple<>, str*>>,closure-0>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\coop.rs:121
  88:     0x7ff7ccd6b323 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<core::result::Result<tuple<>, str*>>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\std\src\thread\local.rs:272
  89:     0x7ff7ccd6b112 - std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<core::result::Result<tuple<>, str*>>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\std\src\thread\local.rs:248
  90:     0x7ff7ccd65df0 - tokio::coop::with_budget
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\coop.rs:114
  91:     0x7ff7ccd65df0 - tokio::coop::budget
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\coop.rs:98
  92:     0x7ff7ccd65df0 - tokio::park::thread::CachedParkThread::block_on<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\park\thread.rs:263
  93:     0x7ff7ccd6acfc - tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\runtime\enter.rs:151
  94:     0x7ff7cccdc213 - tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\runtime\thread_pool\mod.rs:71
  95:     0x7ff7ccd77598 - tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\AdminCOOP\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.0.1\src\runtime\mod.rs:452
  96:     0x7ff7ccce18aa - fluminurs::main
                               at C:\Users\AdminCOOP\Documents\GitHub\fluminurs\src\main.rs:248
  97:     0x7ff7ccd5ac2b - core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, str*>,tuple<>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\ops\function.rs:227
  98:     0x7ff7ccce217b - std::sys_common::backtrace::__rust_begin_short_backtrace<fn() -> core::result::Result<tuple<>, str*>,core::result::Result<tuple<>, str*>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\std\src\sys_common\backtrace.rs:125
  99:     0x7ff7ccd75791 - std::rt::lang_start::{{closure}}<core::result::Result<tuple<>, str*>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\std\src\rt.rs:66
 100:     0x7ff7cd63f463 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\core\src\ops\function.rs:280
 101:     0x7ff7cd63f463 - std::panicking::try::do_call
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:381
 102:     0x7ff7cd63f463 - std::panicking::try
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panicking.rs:345
 103:     0x7ff7cd63f463 - std::panic::catch_unwind
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\panic.rs:396
 104:     0x7ff7cd63f463 - std::rt::lang_start_internal
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\/library\std\src\rt.rs:51
 105:     0x7ff7ccd75763 - std::rt::lang_start<core::result::Result<tuple<>, str*>>
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca\library\std\src\rt.rs:65
 106:     0x7ff7ccce19b0 - main
 107:     0x7ff7cd65bfc0 - invoke_main
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
 108:     0x7ff7cd65bfc0 - __scrt_common_main_seh
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
 109:     0x7ffefb887034 - BaseThreadInitThunk
 110:     0x7ffefd6dd0d1 - RtlUserThreadStart
error: process didn't exit successfully: `target\debug\fluminurs.exe` (exit code: 101)
```

**Comment by JingYenLoh** [comment]
This should be a duplicate of #615 . Sorry for the delay, we have been swamped by Hack&Roll. Will review and merge the relevant PR soon.

**Comment by btzy** [comment]
Sorry, yeah, looks like it is the same issue.
